In [2]:
my_list = [1, 2, 3]

In [1]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# start, stop, number of evenly spaced points between start and stop
np.linspace(0,5,25)

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

In [20]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.89708723, 0.547001  , 0.98144019, 0.04314107, 0.36780774])

In [22]:
np.random.rand(5,5)

array([[0.94704346, 0.99202179, 0.36009562, 0.21385811, 0.70304779],
       [0.5689021 , 0.26197247, 0.94300739, 0.09558486, 0.82551555],
       [0.35077873, 0.56473075, 0.17310803, 0.03115228, 0.30261195],
       [0.95231727, 0.2146009 , 0.03789831, 0.58872573, 0.47815793],
       [0.71196185, 0.12720271, 0.42270158, 0.86774619, 0.16755081]])

In [23]:
np.random.randn(2)

array([1.1212383 , 0.42264482])

In [24]:
np.random.randn(4,4)

array([[-1.31190126,  3.02859178,  0.09109515,  0.22643777],
       [-0.44682754, -0.44105766, -0.27795961,  0.62630036],
       [ 1.73524311,  0.36077557,  0.7280591 , -0.6064045 ],
       [-0.04498221,  0.25297322, -0.07055058,  0.81624077]])

In [27]:
np.random.randint(1,100,10)

array([76, 49,  8, 73, 25, 71, 29, 72, 48, 73])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([ 9,  7, 34, 45, 35, 46,  1, 38, 46, 20])

In [32]:
#reshape method
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
# you'll get an error if you try to create an array with more . . . 
# . . . elements than you start with

In [35]:
ranarr.max()

46

In [36]:
ranarr.min()

1

In [37]:
ranarr

array([ 9,  7, 34, 45, 35, 46,  1, 38, 46, 20])

In [38]:
ranarr.argmax()

5

In [39]:
ranarr.argmin()

6

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [47]:
# creates a reference
from numpy.random import randint

In [46]:
randint(2, 10)

4

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
# broadcast
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
# call original array, not just slice, original is changed = broadcasting
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
# specifying copy
arr_copy = arr.copy()

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
# broadcasts to copy don't change original array

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[0][0]

5

In [35]:
arr_2d[0]

array([ 5, 10, 15])

In [36]:
arr_2d[1][1]

25

In [37]:
arr_2d[2,1]

40

In [38]:
arr_2d[2][1]

40

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [51]:
arr[:6] = np.arange(0,6)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
bool_arr = arr > 5

In [55]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [56]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr<3]

array([0, 1, 2])

In [60]:
arr_2d = np.arange(50).reshape(5,10)

In [61]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
# grab 13, 14 and 23, 24
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [65]:
# Numpy Operations

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# adding arrays on element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [72]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [73]:
# python response to divide by zero error
1 / 0

ZeroDivisionError: division by zero

In [74]:
# numpy response to divide by zero error
arr / arr 

<ipython-input-74-5dd38c744e6f>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [76]:
# universal array functions

In [77]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [79]:
np.max(arr)

10

In [80]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [81]:
np.log(arr)

<ipython-input-81-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])